apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-calculator-leader-election-rolebinding
  namespace: pod-calculator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-calculator-leader-election-role
subjects:
- kind: ServiceAccount
  name: pod-calculator-controller-manager
  namespace: pod-calculator-system
