apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-calculator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-calculator-manager-role
subjects:
- kind: ServiceAccount
  name: pod-calculator-controller-manager
  namespace: pod-calculator-system
