# permissions for end users to view podcalculators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pod-calculator
    app.kubernetes.io/managed-by: kustomize
  name: podcalculator-viewer-role
rules:
- apiGroups:
  - pod.example.com
  resources:
  - podcalculators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pod.example.com
  resources:
  - podcalculators/status
  verbs:
  - get
