---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - pod.example.com
  resources:
  - podcalculators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pod.example.com
  resources:
  - podcalculators/finalizers
  verbs:
  - update
- apiGroups:
  - pod.example.com
  resources:
  - podcalculators/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - v1
  resources:
  - configmap
  verbs:
  - create
  - get
  - list
  - patch
  - update
